# PyMARS Simulation Configuration
# Structured format similar to NML input files

calculation_parameters:
  model: "path/to/fennix_model.fnx"  # Path to FENNIX model file

general_parameters:
  temperature: 300.0  # Temperature in Kelvin
  batch_size: 1  # Number of parallel simulations (trajectories)
  seed: 12345  # Random seed for reproducibility
  save_steps: 100  # Save trajectory frames every N steps
  save_energy: 100  # Save energy data every N steps

input_parameters:
  initial_geometry: "tests/aspirin.xyz"  # Path to initial XYZ geometry
  total_charge: 0  # Total molecular charge
  random_rotation: true  # Apply random rotation to initial configuration

projectile_parameters:
  projectile_flag: true  # Enable projectile collision simulation
  projectile_species: 18  # Atomic number (18 = Argon)
  projectile_temperature: 3000.0  # Projectile temperature in Kelvin
  projectile_distance: 20.0  # Initial projectile distance in angstrom
  max_impact_parameter: 0.5  # Maximum impact parameter in angstrom

thermostat_parameters:
  # Note: NVE_thermostat and LGV_thermostat cannot both be true
  NVE_thermostat: true  # Use NVE (microcanonical) ensemble
  LGV_thermostat: false  # Use Langevin thermostat
  gamma: 0.0  # Friction constant in THz (for Langevin thermostat)

dynamic_parameters:
  dt_dyn: 1.0  # Timestep in femtoseconds (fs)
  step_dyn: 10000  # Total number of MD steps

output_details:
  trajectory_file: "trajectory.xyz"  # Output trajectory file
  # For batch simulations, you can provide a list:
  # trajectory_file:
  #   - "trajectory_0.xyz"
  #   - "trajectory_1.xyz"
  
  energies_file: "energies.out"  # Output energy file
  # For batch simulations, you can provide a list:
  # energies_file:
  #   - "energies_0.out"
  #   - "energies_1.out"

# Energy file format:
#     Step   Time[fs]       Etot       Epot       Ekin    Temp[K]
# Where:
#   Step: Integration step number
#   Time[fs]: Time in femtoseconds
#   Etot: Total energy (kcal/mol)
#   Epot: Potential energy (kcal/mol)
#   Ekin: Kinetic energy (kcal/mol)
#   Temp[K]: Temperature (Kelvin)
